-- [Entity] NYPD
CREATE TABLE NYPD (
		NYPD_PID INTEGER,
    PATRL_BORO_NM_ID INTEGER,
    PATRL_BORO_NM CHAR(50),
    BORO_NM CHAR(20) CHECK (BORO_NM IN ('MANHATTAN','BRONX','QUEENS','BROOKLYN','STATEN ISLAND')),
    PRIMARY KEY(NYPD_PID)
);

-- [Entity] Crime_Scene
CREATE TABLE Crime_Scene (
		CRIME_SCENE_PID INTEGER,
    LOC_OF_OCCUR_DESC CHAR(10),
    PREM_TYP_DESC VARCHAR(30),
    GEO_CD_X REAL CHECK (GEO_CD_X>0),
    GEO_CD_Y REAL CHECK (GEO_CD_Y>0),
    Longitude REAL CHECK (Longitude>=-75 AND Longitude<=-73),
    Latitude REAL CHECK (Latitude>=40 AND Latitude<=41),
    CMPLNT_FR_DT DATE,
    CMPLNT_FR_TM TIME,
    CMPLNT_TO_DT DATE,
    CMPLNT_TO_TM TIME,
    CHECK (CMPLNT_FR_DT<=CMPLNT_TO_DT),
    PRIMARY KEY (CRIME_SCENE_PID)
);

-- [Entity] Incident (10/29 ADD NYPD ID)
CREATE TABLE Incident (
		INCIDENT_PID INTEGER,
    CAD_EVNT_ID INTEGER,
    CIP_JOBS CHAR(20),
    LAW_CAT_CD CHAR(15),
    TYP_DESC VARCHAR(100), -- [Modification] CHAR(100) -> VARCHAR(100)
    PRIMARY KEY (INCIDENT_PID)
);

-- [Relationship] Monitor
CREATE TABLE Monitor (
		NYPD_PID INTEGER,
		INCIDENT_PID INTEGER,
		JURIS_DESC CHAR(20),
		CREATE_DATE TIMESTAMP,
		ADDED_TIME TIMESTAMP,
		CLOSING_TS TIMESTAMP,
		CHECK (JURIS_DESC IN ('N.Y. POLICE DEPT','N.Y. TRANSIT POLICE')),
    PRIMARY KEY (NYPD_PID, INCIDENT_PID),
    FOREIGN KEY (NYPD_PID) REFERENCES NYPD (NYPD_PID),
    FOREIGN KEY (INCIDENT_PID) REFERENCES Incident (INCIDENT_PID)
);
-- Cannot capture a participation constraint of Incident (yet) in SQL

-- << TERNARY >>
-- [Entity] Radio_Code
CREATE TABLE Radio_Code (
    RADIO_CODE_PID INTEGER,
    RADIO_CODE CHAR(5),
    PRIMARY KEY (RADIO_CODE_PID)
);

-- [Relationship] Send
CREATE TABLE Send (
		INCIDENT_PID INTEGER,
		NYPD_PID INTEGER,
		RADIO_CODE_PID INTEGER NOT NULL,
    PRIMARY KEY (INCIDENT_PID, NYPD_PID),
    FOREIGN KEY (INCIDENT_PID) REFERENCES Incident (INCIDENT_PID),
    FOREIGN KEY (NYPD_PID) REFERENCES NYPD (NYPD_PID),
    FOREIGN KEY (RADIO_CODE_PID) REFERENCES Radio_Code (RADIO_CODE_PID)
);
-- Cannot capture a participation constraint of Incident (yet) in SQL

-- << TERNARY >>
-- [Entity] Dispatch_Duration
CREATE TABLE Dispatch_Duration (
		DISPATCH_DURATION_PID INTEGER,
    DISP_TS TIMESTAMP,
    ARRIVD_TS TIMESTAMP,
    CHECK (DISP_TS <= ARRIVD_TS),
    PRIMARY KEY (DISPATCH_DURATION_PID)
);

-- [Relationship] Arrive
CREATE TABLE Arrive (
		CRIME_SCENE_PID INTEGER,
    NYPD_PID INTEGER,
    DISPATCH_DURATION_PID INTEGER,
    PRIMARY KEY (CRIME_SCENE_PID, NYPD_PID, DISPATCH_DURATION_PID),
    FOREIGN KEY (CRIME_SCENE_PID) REFERENCES Crime_Scene (CRIME_SCENE_PID),
    FOREIGN KEY (NYPD_PID) REFERENCES NYPD (NYPD_PID),
    FOREIGN KEY (DISPATCH_DURATION_PID) REFERENCES Dispatch_Duration (DISPATCH_DURATION_PID)
)
-- Cannot capture participation constraints of Crime_Cine and Dispatch_Duration (yet) in SQL
;

-- [Relationship] Occured
CREATE TABLE Occured (
		CRIME_SCENE_PID INTEGER,
		INCIDENT_PID INTEGER NOT NULL,
		PRIMARY KEY (CRIME_SCENE_PID),
		UNIQUE (INCIDENT_PID),
		FOREIGN KEY (CRIME_SCENE_PID) REFERENCES Crime_Scene (CRIME_SCENE_PID),
		FOREIGN KEY (INCIDENT_PID) REFERENCES Incident (INCIDENT_PID)
);
